### PR TITLE
Fix drafts

### PR DESCRIPTION
**Pull request by Khaledgarbaya**
fixes https://github.com/contentful/contentful-export/issues/23

### CODE REVIEW

**Comment by apaatsio** [comment]
I wanted to test this, but I can't install it with npm because there is no version number in package.json.

name and version and required fields in package.json. See https://docs.npmjs.com/files/package.json#version

```
❯ npm install --save git://github.com/contentful/contentful-export.git#fix-drafts
npm ERR! addLocal Could not install /tmp/npm-8889-5ee455cf/git-cache-aaae5c08ca56/b17495deb1ed5a4aacbde3b145bd060d4b4e11d6
npm ERR! Linux 4.8.14-1-MANJARO
npm ERR! argv "/home/antti/.nvm/versions/node/v4.6.2/bin/node" "/home/antti/.nvm/versions/node/v4.6.2/bin/npm" "install" "--save" "git://github.com/contentful/contentful-export.git#fix-drafts"
npm ERR! node v4.6.2
npm ERR! npm  v2.15.11

npm ERR! No version provided in package.json
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/antti/my-project/npm-debug.log
```

**Comment by Khaledgarbaya** [comment]
@apaatsio we use semantic release for the package, that's why there is no version in the package.json, can just add a version field or `npm install && npm run build` and then use `./bin/contentful-export --config config.js`

**Comment by apaatsio** [comment]
Ok, thanks! 

semantic-version itself seems to use `"version": "0.0.0-placeholder"` in their package.json.  https://github.com/semantic-release/semantic-release/blob/caribou/package.json#L4

**Comment by Khaledgarbaya** [comment]
@apaatsio sorry for the confusion, yes make sense to have something like that

**Comment by Khaledgarbaya** [comment]
@apaatsio can you test with this PR if you still have the issue

**Comment by apaatsio** [comment]
Works for me :+1:

**Comment by Khaledgarbaya** [comment]
Great I will merge the fix asap

**Pull request merged**
