### PR TITLE
[SEC-1561] chore: add coverity scan to the pipeline

### PR DESCRIPTION
**Pull request by fkiriakos**

### CODE REVIEW

**Review by phoebeschmidt — APPROVED** [review]
Looks okay to me, but let's have @ruderngespra also approve :)

**Review by ruderngespra — APPROVED** [review]
:+1:

**Comment by ruderngespra** [comment]
But maybe wait with merging until after the freeze? :thinking:

**Comment by fkiriakos** [comment]
Thank you for the review, since we are only changing the circleCI config, the changes do not need to be deployed but if you think it would be better to wait after the freeze, then it should be fine.

**Pull request merged**
