### PR TITLE
use file.end() instead of file.close()

### PR DESCRIPTION
**Pull request by iddan**
This is the officially supported non breaking API.
Tested on node 9.2.0

### CODE REVIEW

**Comment by axe312ger** [comment]
Thank you. This is already fixed in the upcomming version as you can see here:
https://github.com/contentful/contentful-export/blob/next/lib/download-asset.js#L42

We are planning to release it asap. You are very welcome to give it a test: `npm install -g contentful-export@next`

**Comment by axe312ger** [comment]
Ohh no, sorry. I was to fast with that one, you are totally correct here.

Would you mind to change your PR to apply to next branch instead of master? It will then straight go into the next version :)

**Comment by iddan** [comment]
For some reason it diffs the readme

**Comment by axe312ger** [comment]
Yeah cus that one commit was not rebased yet into next. Should be fine. I do some checks and merge afterwards. Thank you a lot!

**Comment by axe312ger** [comment]
Tested it on `v6.11.1` and it worked fine. Merging :)

**Pull request merged**
